### ISSUE TITLE
无法删除命令

### ISSUE THREAD

**Issue by AugustToko** [Nightmare-MY/flutter_toolkit#1]
### 按下软键盘 backspace 无法删除命令
![P39%IZ@2C49Q(YTDQJ$DNET](https://user-images.githubusercontent.com/20200460/75123807-c02e9800-56e5-11ea-9270-641a86c71e71.png)

### log:
![F@~3QY68QTV(UY9S2`3(S15](https://user-images.githubusercontent.com/20200460/75123817-cf154a80-56e5-11ea-9b15-e042f6447ddb.png)

**Comment by Nightmare-MY** [comment]
这个解决了
